version: '3.8'

services:
  caddy:
    image: caddy:2.3.0-alpine
    container_name: ghost-prod-caddy
    depends_on:
      - ghost
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - ghost_caddy_data:/data
      - ghost_caddy_config:/config

  ghost:
    image: ghost:4.3.3-alpine
    container_name: ghost-prod
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: ${MYSQL_USER}
      database__connection__password: ${MYSQL_PASSWORD}
      database__connection__database: ${MYSQL_DATABASE}
      url: https://your-domain-name
    volumes:
      - ghost_content:/var/lib/ghost/content

  db:
    image: mysql:8
    container_name: ghost-prod-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      # see https://hub.docker.com/_/mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_ghost_data:/var/lib/mysql

volumes:
  mysql_ghost_data:
  ghost_content:
  ghost_caddy_data:
  ghost_caddy_config: